### ISSUE TITLE
error storing apikey

### ISSUE THREAD

**Issue by knewson** [mthyden/PhillipsHueSIMPLSharp#13] opened 2018-10-01 21:26 UTC
Hello, Everything seems to work well when I initialize, but I have to pair the unit on every boot. I get the following

No local API key stored
registering with bridge...
error storing apikey
Bridge registration complete

I'm using a MC3 with up-to-date firmware and up-to-date software

**Comment by mthyden** [comment] 2018-10-02 00:35
Sounds like a possible datastore issue when the api key was first attempted to be written. I’m not sure if there is a more targeted way to clear out a single program instance as it relates to its local datastore but an initialize will flush the system. I believe this occurred to someone else and they were able to recover after the initialize.

**Comment by knewson** [comment] 2018-10-02 22:30
I've tried an init a couple times and still come up with the same issue. 

More Info:
Exception is System.ArgumentOutOfRangeException:
Parameter name: index 
   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at System.Collections.Generic.List`1.get_Item(Int32 index)
   at Crestron.SimplSharp.CrestronDataStore.CrestronDataStoreStatic.i(Boolean A_0)
   at Crestron.SimplSharp.CrestronDataStore.CrestronDataStoreStatic.GetLocalStringValue(String tag, String& value)
   at HueLights.HueBridge.GetDataStore()
   at HueLights.HueProc.Register()
   at UserModule_HUELIGHTSPROC_R1_5.UserModuleClass_HUELIGHTSPROC_R1_5.GETREGISTER_OnPush_1(Object __EventInfo__)
   at Amib.Threading.Internal.WorkItem.o()
   at Amib.Threading.Internal.WorkItem.Execute()
   at Amib.Threading.SmartThreadPool.e(WorkItem A_0)
   at Amib.Threading.SmartThreadPool.p()
Get IP of Bridge complete...
No local API key stored
registering with bridge...
error storing apikey
Bridge registration complete
9 Bulbs discovered
1 Rooms discovered
11 Scenes discovered

**Comment by mthyden** [comment] 2018-10-03 13:57
Hmm, I’ll have to try this on my MC3 with the latest firmware. Previously this has worked on MC3s but I haven’t tested it on the latest. Do you have any other modules in your program that are simplsharp based using the datastore?

**Comment by knewson** [comment] 2018-10-03 15:09
I don't

**Comment by mthyden** [comment] 2018-10-03 15:13
Can you do me a favor and type from console datastorestatus and reply with the response

Should something similar to  this:
DIN-AP3MEX>datastorestatus
CrestronDataStore: SIMPLLOCAL          2 records  
	Main	  1 records 	 116 bytes 	 1% used 
	Lighting	  1 records 	 124 bytes 	 1% used 
CrestronDataStore: SIMPLGLOBAL          0 records

**Comment by knewson** [comment] 2018-10-03 15:14
MC3>datastorestatus
DataStores not Available

**Comment by mthyden** [comment] 2018-10-04 14:59
Tested DataStore setup/read/write on an MC3 with latest firmware, seems to check out. In my current release ver of the module I don’t have any advanced error checking to see what the exact error is when the DataStore is first getting setup but could add a quick mod perhaps later today and send you a new CLZ. You may want to delay your init from SIMPL as the MC3 takes long to settle after boot. As a test you could throw in a 10 sec delay on program start to the Primary module init or something similar.

**Comment by knewson** [comment] 2018-10-04 21:17
Had a chat with TrueBlue, They confirmed DataStore wasn't working on any of their test MC3's. A ticket is created to find out why but it may not be possible...Can you modify the # to allow me to send the key from the program? Then I can store and send on program start

**Comment by mthyden** [comment] 2018-10-04 21:31
Like I did confirm DataStore read/write access this morning on my MC3 in my office, running release firmware so that is not the issue unless the problem is the initial creation of the datastore with current firmware where an existing datastore if created and upgraded doesn’t work as expected. What is the true blue support ticket number so I can follow up with them.

Yeah, I can modify the proc module to accept a key from the parameter field. Gonna be a few days as I am traveling to our HQ this weekend.

**Comment by knewson** [comment] 2018-10-04 21:32
TrueBlue Incident #181003-000553. No worries. It's working great for now. Really well done!

**Comment by mthyden** [comment] 2018-12-22 16:53
going to close this as it appears to be localized to the MC3 hw platform. this week I plan to add a field to allow folks to insert their API key after pairing so if the parameter field is populated will use that rather then the datastore. stay tuned

**Closed as completed by mthyden** 2018-12-22 16:53 UTC
