### ISSUE TITLE
White ambiance bulb cant adjust kelvin

### ISSUE THREAD

**Issue by Phimour** [mthyden/PhillipsHueSIMPLSharp#28] opened 2020-11-23 19:54 UTC
Neither hue og saturation does a difference. 

Philips Hue bridge 2
Philips Hue White Ambiance E27

**Comment by mthyden** [comment] 2020-11-24 11:27
When this was first developed The Hue / Sat were for color changing not to adjust the white ambient, my equipment is currently in transit as I recently moved so won’t be able to look into this for a few weeks but I suspect its not working with that bulb type as I do a color mode property check preventing hue/sat values for passing to bulbs that aren’t color supported.

**Comment by mthyden** [comment] 2020-12-09 19:25
I thought I had a White Ambiance E27 in my bulb list but I don’t, if you can provide the JSON data from your bridge with the Lights array and send it back to me that would be helpful so I can improve the support for that bulb type.

Thanks,

Monte

**Comment by Phimour** [comment] 2020-12-09 19:53
Hello Monte. 

How do I provide the JSON data for you? 😊 

 

Best regards 

 

Philip

**Comment by mthyden** [comment] 2020-12-09 19:56
https://developers.meethue.com/develop/get-started-2/ <https://developers.meethue.com/develop/get-started-2/>

You can substitute the api key with the string output from the module for debug purposes

In the clip.html add lights to the end of the command and hit get, that should then return the json array of your bulbs

**Comment by mthyden** [comment] 2020-12-09 20:00
And since the bulb you are dealing with isn’t color I believe saturation / brightness will be your only adjustment on it.

**Comment by Phimour** [comment] 2020-12-09 20:13
Hello Monte. 



I think I got it here.  – I am pretty sure it’s the top one

{

                "3": {

                                "state": {

                                                "on": true,

                                                "bri": 254,

                                                "ct": 366,

                                                "alert": "none",

                                                "colormode": "ct",

                                                "mode": "homeautomation",

                                                "reachable": false

                                },

                                "swupdate": {

                                                "state": "noupdates",

                                                "lastinstall": "2020-11-23T19:42:46"

                                },

                                "type": "Color temperature light",

                                "name": "soveværelse",

                                "modelid": "LTA001",

                                "manufacturername": "Signify Netherlands B.V.",

                                "productname": "Hue ambiance lamp",

                                "capabilities": {

                                                "certified": true,

                                                "control": {

                                                                "mindimlevel": 200,

                                                                "maxlumen": 800,

                                                                "ct": {

                                                                                "min": 153,

                                                                                "max": 454

                                                                }

                                                },

                                                "streaming": {

                                                                "renderer": false,

                                                                "proxy": false

                                                }

                                },

                                "config": {

                                                "archetype": "sultanbulb",

                                                "function": "functional",

                                                "direction": "omnidirectional",

                                                "startup": {

                                                                "mode": "safety",

                                                                "configured": true

                                                }

                                },

                                "uniqueid": "00:17:88:01:08:b0:2d:b6-0b",

                                "swversion": "1.65.9_hB3217DF",

                                "swconfigid": "DF3903E5",

                                "productid": "Philips-LTA001-2-A19CTv3"

                },

                "4": {

                                "state": {

                                                "on": true,

                                                "bri": 254,

                                                "alert": "none",

                                                "mode": "homeautomation",

                                                "reachable": true

                                },

                                "swupdate": {

                                                "state": "noupdates",

                                                "lastinstall": "2020-12-03T13:52:26"

                                },

                                "type": "Dimmable light",

                                "name": "værelse gård",

                                "modelid": "LWA001",

                                "manufacturername": "Signify Netherlands B.V.",

                                "productname": "Hue white lamp",

                                "capabilities": {

                                                "certified": true,

                                                "control": {

                                                                "mindimlevel": 5000,

                                                                "maxlumen": 800

                                                },

                                                "streaming": {

                                                                "renderer": false,

                                                                "proxy": false

                                                }

                                },

                                "config": {

                                                "archetype": "sultanbulb",

                                                "function": "functional",

                                                "direction": "omnidirectional",

                                                "startup": {

                                                                "mode": "safety",

                                                                "configured": true

                                                }

                                },

                                "uniqueid": "00:17:88:01:06:e3:0f:94-0b",

                                "swversion": "1.65.9_hB3217DF",

                                "swconfigid": "44288730",

                                "productid": "Philips-LWA001-1-A19DLv5"

                }

**Comment by mthyden** [comment] 2020-12-09 20:30
Ok thanks, I’ll take a look

**Comment by mthyden** [comment] 2020-12-27 16:45
Apologies for the delay on this. I actually ended up ordering one of those non color ambient bulbs so I can test here which should arrive in a day or two. I added some error checking to see what the response from the bridge was when sending a saturation value through my bulb module to a non color non saturation capable bulb and the bridge did correctly indicate that it didn’t support saturation, which at the very least tells me that if you are using the individual bulb module adjusting Sat value should be going through all my logic. Originally I had some validation checks preventing it but I must have removed those years ago.

One thing I am curious about is if you have that bulb type in a room and you adjust the room Sat value will that work? And the issue is only when trying to adjust the bulb only? 

Like I said I should be able to verify and fix very easily once I get that new bulb here soon.

**Comment by mthyden** [comment] 2020-12-27 17:07
Totally misunderstood the issue you reported until now, I need to add the “ct” parameter to the room and bulb module, will get these added here shortly.

**Comment by mthyden** [comment] 2020-12-27 18:51
This feature has been added and tested both the Room and Bulb modules have been modified to support this new feature.

**Comment by mthyden** [comment] 2020-12-27 18:51
resolved in latest commit

**Closed as completed by mthyden** 2020-12-27 18:51 UTC
